// Shaders en strings normales para evitar problemas de Babel con #version en template literals

export const trailVS = [
  '#version 300 es',
  'in vec2 aPos;',
  'out vec2 vUV;',
  'void main() {',
  '  vUV = aPos * 0.5 + 0.5;',
  '  gl_Position = vec4(aPos, 0.0, 1.0);',
  '}',
].join('\n')

export const trailFS = [
  '#version 300 es',
  'precision mediump float;',
  'in vec2 vUV;',
  'uniform sampler2D uPrevTrail;',
  'uniform vec2      uMouse;',
  'uniform float     uBrushRadius;',
  'uniform float     uFade;',
  'out vec4 outColor;',
  'void main() {',
  '  float prev  = texture(uPrevTrail, vUV).r * uFade;',
  '  float d     = distance(vUV, uMouse);',
  '  float brush = smoothstep(uBrushRadius, uBrushRadius * 0.3, d);',
  '  float val   = clamp(prev + brush, 0.0, 1.0);',
  '  outColor    = vec4(val, val, val, 1.0);',
  '}',
].join('\n')

export const rainVS = [
  '#version 300 es',
  'in vec4 aVertexPosition;',
  'in vec2 aTextureCoord;',
  'uniform mat4 uMVMatrix;',
  'uniform mat4 uPMatrix;',
  'uniform mat4 dispImageMatrix;',
  'out vec3 vVertexPosition;',
  'out vec2 vTextureCoord;',
  'void main() {',
  '  gl_Position   = uPMatrix * uMVMatrix * aVertexPosition;',
  '  vTextureCoord = (dispImageMatrix * vec4(aTextureCoord, 0., 1.)).xy;',
  '  vVertexPosition = aVertexPosition.xyz;',
  '}',
].join('\n')

export const rainFS = [
  '#version 300 es',
  'precision mediump float;',
  '#define PI2 6.28318530718',
  '#define PI  3.14159265359',
  '#define S(a,b,n) smoothstep(a,b,n)',
  'in vec3 vVertexPosition;',
  'in vec2 vTextureCoord;',
  'uniform float uTime;',
  'uniform vec2  uReso;',
  'uniform vec2  uMouse;',
  'uniform sampler2D dispImage;',
  'uniform sampler2D trailImage;',
  'out vec4 outColor;',

  'float N12(vec2 p){',
  '  p = fract(p * vec2(123.34, 345.45));',
  '  p += dot(p, p + 34.345);',
  '  return fract(p.x * p.y);',
  '}',

  'vec3 Layer(vec2 uv0, float t){',
  '  vec2 asp = vec2(2., 1.);',
  '  vec2 uv1 = uv0 * 3. * asp;',
  '  uv1.y += t * .25;',
  '  vec2 gv = fract(uv1) - .5;',
  '  vec2 id = floor(uv1);',
  '  float n = N12(id);',
  '  t += n * PI2;',
  '  float w = uv0.y * 10.;',
  '  float x = (n - .5) * .8;',
  '  x += (.4 - abs(x)) * sin(3. * w) * pow(sin(w), 6.) * .45;',
  '  float y = -sin(t + sin(t + sin(t) * .5)) * (.5 - .06);',
  '  y -= (gv.x - x) * (gv.x - x);',
  '  vec2 dropPos  = (gv - vec2(x, y)) / asp;',
  '  float drop    = S(.04, .01, length(dropPos));',
  '  vec2 trailPos = (gv - vec2(x, t * .25)) / asp;',
  '  trailPos.y = (fract(trailPos.y * 8.) - .5) / 8.;',
  '  float trail    = S(.02, .015, length(trailPos));',
  '  float fogTrail = S(-.05, .05, dropPos.y);',
  '  fogTrail *= S(.9, y, gv.y);',
  '  trail    *= fogTrail;',
  '  fogTrail *= S(.03, .015, abs(dropPos.x));',
  '  vec2 off = drop * dropPos + trail * trailPos;',
  '  return vec3(off, fogTrail);',
  '}',

  'void main() {',
  '  float dist     = 5.;',
  '  float blurSize = 5.;',
  '  float t = mod(uTime * 4.13, 7200.);',
  '  vec2 uv = vTextureCoord;',
  '  float wipeMask = texture(trailImage, uv).r;',
  '  vec3 drops = Layer(uv, t);',
  '  drops += Layer(uv * 1.25 + 0.54,  t);',
  '  drops += Layer(uv * 1.35 + 11.54, t);',
  '  drops += Layer(uv * 1.57 - 17.54, t);',
  '  float blur = blurSize * 5. * (3. - drops.z);',
  '  vec4  col  = vec4(0.);',
  '  float a    = N12(uv) * PI2;',
  '  blur *= .0002;',
  '  vec2 uvDisp = uv + drops.xy * dist;',
  '  for(int n = 0; n < 25; n++){',
  '    vec2  off = vec2(sin(a), cos(a)) * blur;',
  '    float d   = fract(sin((float(n) + 1.) * 546.) * 5424.);',
  '    d = sqrt(d);',
  '    off *= d;',
  '    col += texture(dispImage, vec2(uvDisp.x + off.x, 1.0 - uvDisp.y - off.y));',
  '    a++;',
  '  }',
  '  col /= float(25);',
  '  vec4 clearWithDrops = texture(dispImage, vec2(uvDisp.x, 1.0 - uvDisp.y));',
  '  outColor = mix(col, clearWithDrops, wipeMask);',
  '}',
].join('\n')